### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by josepaulo10** [ThiagoBarradas/jsonmasking#3]

**Comment by ThiagoBarradas** [comment]
Hello?

**Comment by marioreis00** [comment]
Hello! How are you?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Thiago Barradas <notifications@github.com>
Enviado: Friday, July 3, 2020 2:44:31 AM
Para: ThiagoBarradas/jsonmasking <jsonmasking@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [ThiagoBarradas/jsonmasking] AppVeyor (#3)


Hello?

**Comment by josepaulo10** [comment]
> Hello?

Olá Thiago Barradas! Tudo bem? Eu sou aluno da Digital  Innovation One. Eu gostei muito da sua aula de arquitetura de sistemas avançado. Você poderia mim enviar aqueles slides por e-mail?

**Comment by ThiagoBarradas** [comment]
Olá, claro! Perdão a demora, estou esses dias sem responder as issues por aqui!

O seu email é USA_0007@hotmail.com?

**Comment by josepaulo10** [comment]
Positivo este é meu e-mail USA_0007@hotmail.com Thiago. Muito obrigado

**Comment by ThiagoBarradas** [comment]
Enviado! Abraço!

**Comment by josepaulo10** [comment]
Obrigado Thiago. Abraços

Obter o Outlook<https://aka.ms/qtex0l> para iOS
________________________________
De: Thiago Barradas <notifications@github.com>
Enviado: Wednesday, July 29, 2020 2:29:15 PM
Para: ThiagoBarradas/jsonmasking <jsonmasking@noreply.github.com>
Cc: josepaulo10 <USA_0007@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [ThiagoBarradas/jsonmasking] AppVeyor (#3)


Closed #3<https://github.com/ThiagoBarradas/jsonmasking/issues/3>.
